development:
  adapter: postgresql
  encoding: unicode
  database: badcomics_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: badcomics_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: badcomics_production
  host:
  pool: 5
