development:
  adapter: postgresql
  encoding: unicode
  database: badcomics_development
  host: localhost
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: badcomics_test
  host: localhost
  pool: 5
  username: myapp
  password: password1

staging:
  adapter: postgresql
  encoding: unicode
  database: badcomics_staging
  host: localhost
  pool: 5
  username: myapp
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: badcomics_production
  host: localhost
  pool: 5
  username: myapp
  password: password1
