development:
  adapter: postgresql
  encoding: unicode
  database: badcomics_development
  host: localhost
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: badcomics_test
  host: localhost
  pool: 5
  username: myapp
  password: password1

staging:
  adapter: sqlite3
  database: db/staging.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: badcomics_production
  host: localhost
  pool: 5
  username: myapp
  password: password1
